// addProducts.js ke andar badlav karein
import { addDoc, collection } from "firebase/firestore";
import { db } from "./src/pages/config/firebase.js"; // Extension .js hona zaroori hai

const products = [
  // Chakla Products
  {
    id: 1,
    name: "Premium Yellow Wooden Chakla",
    slug: "premium-yellow-wooden",
    category: "Chakla",
    price: 55,
    oldPrice: 75,
    discount: 27,
    stock: 45,
    rating: 4.8,
    reviews: 128,
    brand: "AG Traders",
    material: "Hardwood",
    color: "Yellow Polish",
    weight: "200g",
    diameter: "9 inch",
    image: "/src/assets/Images/yellow.png",
    description:
      "Premium quality yellow polished wooden chakla made from strong hardwood. Smooth finish, comfortable grip and perfect for daily roti, paratha and puri making.",
    features: [
      "Anti-slip surface",
      "Eco-friendly",
      "Lifetime durability",
      "Smooth finish",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 2,
    name: "Double Polish Neem Chakla",
    slug: "double-polish-neem-chakla",
    category: "Chakla",
    price: 65,
    oldPrice: 90,
    discount: 28,
    stock: 50,
    rating: 4.9,
    reviews: 210,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Dark Brown",
    weight: "300g",
    diameter: "10 inch",
    image: "/src/assets/Images/neemCakla.png",
    description:
      "Premium neem wood chakla with natural anti-bacterial properties. Double polished for smooth surface and long-lasting durability.",
    features: [
      "Anti-bacterial",
      "Double polished",
      "Premium finish",
      "Eco-friendly",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 3,
    name: "Akand Premium Chakla",
    slug: "akand-premium-chakla",
    category: "Chakla",
    price: 95,
    oldPrice: 129,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Akand Wood",
    color: "Light White",
    weight: "250g",
    diameter: "10 inch",
    image: "/src/assets/Images/akandCakala.png",
    description:
      "Premium Akand wood chakla with exceptional durability and smooth finish. Best choice for professional use.",
    features: [
      "Premium Akand wood",
      "Extra durable",
      "Smooth surface",
      "Professional use",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 4,
    name: "Sarmika Wooden Chakla",
    slug: "sarmika-wooden-chakla",
    category: "Chakla",
    price: 34,
    oldPrice: 47,
    discount: 28,
    stock: 500,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Sarmika Wood",
    color: "Light Brown",
    weight: "200g",
    diameter: "9 inch",
    image: "/src/assets/Images/sarmika.png",
    description:
      "Premium Sarmika wood chakla with natural grains and strong body. Long-lasting and perfect balance for smooth rolling.",
    features: ["Smooth surface", "Lightweight", "Durable", "Natural wood"],
    shippingTime: "3-5 days",
  },
  {
    id: 5,
    name: "Sarmika Premium Chakla",
    slug: "sarmika-premium-chakla",
    category: "Chakla",
    price: 42,
    oldPrice: 58,
    discount: 28,
    stock: 300,
    rating: 4.6,
    reviews: 180,
    brand: "AG Traders",
    material: "Sarmika Wood",
    color: "Natural Brown",
    weight: "220g",
    diameter: "9.5 inch",
    image: "/src/assets/Images/sarmikaa.png",
    description:
      "High-quality Sarmika wood chakla with enhanced durability and smooth finish. Perfect for professional cooking.",
    features: [
      "Premium quality",
      "Enhanced durability",
      "Smooth finish",
      "Professional grade",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 6,
    name: "Neem Wood Chakla",
    slug: "neem-wood-chakla",
    category: "Chakla",
    price: 48,
    oldPrice: 65,
    discount: 26,
    stock: 400,
    rating: 4.5,
    reviews: 150,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Natural Brown",
    weight: "180g",
    diameter: "8.5 inch",
    image: "/src/assets/Images/neem.png",
    description:
      "Traditional neem wood chakla with natural anti-bacterial properties. Ideal for healthy cooking.",
    features: [
      "Anti-bacterial",
      "Natural wood",
      "Traditional design",
      "Healthy cooking",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 7,
    name: "Neem Special Chakla",
    slug: "neem-special-chakla",
    category: "Chakla",
    price: 52,
    oldPrice: 70,
    discount: 26,
    stock: 350,
    rating: 4.7,
    reviews: 190,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Special Finish",
    weight: "210g",
    diameter: "9 inch",
    image: "/src/assets/Images/neems.png",
    description:
      "Special finish neem wood chakla with enhanced smoothness and durability. Perfect for daily use.",
    features: ["Special finish", "Enhanced smoothness", "Durable", "Daily use"],
    shippingTime: "3-5 days",
  },
  {
    id: 8,
    name: "Marble Finish Chakla",
    slug: "marble-finish-chakla",
    category: "Chakla",
    price: 78,
    oldPrice: 105,
    discount: 26,
    stock: 200,
    rating: 4.8,
    reviews: 220,
    brand: "AG Traders",
    material: "Marble Wood",
    color: "Marble Pattern",
    weight: "280g",
    diameter: "10 inch",
    image: "/src/assets/Images/marbal.png",
    description:
      "Elegant marble finish chakla with unique pattern and superior quality. A premium addition to your kitchen.",
    features: [
      "Marble finish",
      "Unique pattern",
      "Superior quality",
      "Elegant design",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 9,
    name: "Marble Premium Chakla",
    slug: "marble-premium-chakla",
    category: "Chakla",
    price: 85,
    oldPrice: 115,
    discount: 26,
    stock: 180,
    rating: 4.9,
    reviews: 240,
    brand: "AG Traders",
    material: "Premium Marble Wood",
    color: "Premium Marble",
    weight: "300g",
    diameter: "10.5 inch",
    image: "/src/assets/Images/marbal.png.jpg",
    description:
      "Premium marble wood chakla with exquisite finish and unmatched durability. For the discerning chef.",
    features: [
      "Premium marble",
      "Exquisite finish",
      "Unmatched durability",
      "Chef's choice",
    ],
    shippingTime: "3-5 days",
  },

  // Belan Products
  {
    id: 10,
    name: "White Natural Belan",
    slug: "white-natural-belan",
    category: "Belan",
    price: 16,
    oldPrice: 20,
    discount: 20,
    stock: 30,
    rating: 4.6,
    reviews: 96,
    brand: "AG Traders",
    material: "Wood",
    color: "Natural White",
    weight: "100g",
    length: "12 inch",
    image: "/src/assets/Images/whiteBelan.png",
    description:
      "Heavy and durable wooden belan with smooth surface. Anti-bacterial natural wood, perfect for daily kitchen use.",
    features: ["Lightweight", "Non-toxic", "Easy to clean", "Perfect balance"],
    shippingTime: "3-5 days",
  },
  {
    id: 11,
    name: "Premium White Wood Belan",
    slug: "premium-white-wood-belan",
    category: "Belan",
    price: 18,
    oldPrice: 24,
    discount: 25,
    stock: 50,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Polished Wood",
    color: "Light White",
    weight: "500g",
    length: "9 inch",
    image: "/src/assets/Images/whiteLine.png",
    description:
      "Premium wood belan with natural grains and strong body. Long-lasting and perfect balance for smooth rolling.",
    features: [
      "Natural grain patterns",
      "Smooth rolling",
      "Durable",
      "Professional grade",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 12,
    name: "Double Polish Belan",
    slug: "double-polish-belan",
    category: "Belan",
    price: 65,
    oldPrice: 90,
    discount: 28,
    stock: 50,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Light Brown",
    weight: "200g",
    length: "10 inch",
    image: "/src/assets/Images/Specialbelan.png",
    description:
      "Premium neem wood belan with double polishing process. Strong, durable, and perfect for professional kitchen use.",
    features: [
      "Neem wood benefits",
      "Double polished",
      "Durable",
      "Professional quality",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 13,
    name: "Polish Belan 14 Inch",
    slug: "polish-belan-14-inch",
    category: "Belan",
    price: 22,
    oldPrice: 30,
    discount: 27,
    stock: 500,
    rating: 4.7,
    reviews: 212,
    brand: "AG Traders",
    material: "Polish Wood",
    color: "Light White",
    weight: "130g",
    length: "14 inch",
    image: "/src/assets/Images/14inchbelan.png",
    description:
      "Premium wooden belan with natural grains and strong body. Long-lasting and perfect balance for smooth rolling of dough.",
    features: ["Extra long", "Lightweight", "Smooth rolling", "Easy grip"],
    shippingTime: "3-5 days",
  },
  {
    id: 14,
    name: "Babol Polish Belan 12 Inch",
    slug: "babol-polish-belan-12-inch",
    category: "Belan",
    price: 22,
    oldPrice: 30,
    discount: 27,
    stock: 500,
    rating: 4.7,
    reviews: 212,
    brand: "AG Traders",
    material: "Babol Wood",
    color: "Light White",
    weight: "130g",
    length: "12 inch",
    image: "/src/assets/Images/babol2.png",
    description:
      "Premium Babol wood belan with smooth polishing. Perfect balance and strength for daily kitchen use.",
    features: [
      "Babol wood quality",
      "Well-balanced",
      "Smooth finish",
      "Durable",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 15,
    name: "Babol Gool Belan",
    slug: "babol-gool-belan",
    category: "Belan",
    price: 24,
    oldPrice: 32,
    discount: 25,
    stock: 500,
    rating: 4.8,
    reviews: 215,
    brand: "AG Traders",
    material: "Babol Gool Wood",
    color: "Light White",
    weight: "130g",
    length: "12 inch",
    image: "/src/assets/Images/goolbelan.png",
    description:
      "Premium Babol Gool wood belan with exceptional smoothness. Professional grade quality for perfect roti rolling.",
    features: [
      "Premium quality",
      "Smooth surface",
      "Long-lasting",
      "Professional grade",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 16,
    name: "Gool Belan Polish Premium",
    slug: "gool-belan-polish-premium",
    category: "Belan",
    price: 26,
    oldPrice: 35,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Babool Gool Wood",
    color: "Brown",
    weight: "150g",
    length: "12 inch",
    image: "/src/assets/Images/babolgool.png",
    description:
      "Premium Gool Belan wood with natural grains and strong body. Excellent for professional kitchen use.",
    features: [
      "Premium wood",
      "Smooth rolling",
      "Durable construction",
      "Professional quality",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 17,
    name: "Classic Wooden Belan",
    slug: "classic-wooden-belan",
    category: "Belan",
    price: 14,
    oldPrice: 18,
    discount: 22,
    stock: 600,
    rating: 4.4,
    reviews: 140,
    brand: "AG Traders",
    material: "Wood",
    color: "Natural",
    weight: "90g",
    length: "11 inch",
    image: "/src/assets/Images/belan.png",
    description:
      "Classic wooden belan with traditional design. Perfect for everyday cooking needs.",
    features: ["Traditional design", "Everyday use", "Affordable", "Reliable"],
    shippingTime: "3-5 days",
  },
  {
    id: 18,
    name: "Brown Wooden Belan",
    slug: "brown-wooden-belan",
    category: "Belan",
    price: 19,
    oldPrice: 25,
    discount: 24,
    stock: 450,
    rating: 4.5,
    reviews: 170,
    brand: "AG Traders",
    material: "Wood",
    color: "Brown",
    weight: "110g",
    length: "12 inch",
    image: "/src/assets/Images/belanBrown.png",
    description:
      "Beautiful brown wooden belan with natural wood finish. Strong and durable for daily use.",
    features: [
      "Natural finish",
      "Strong construction",
      "Daily use",
      "Beautiful design",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 19,
    name: "Babol Premium Belan",
    slug: "babol-premium-belan",
    category: "Belan",
    price: 28,
    oldPrice: 38,
    discount: 26,
    stock: 400,
    rating: 4.8,
    reviews: 230,
    brand: "AG Traders",
    material: "Babol Wood",
    color: "Premium Finish",
    weight: "140g",
    length: "13 inch",
    image: "/src/assets/Images/babol belan.png",
    description:
      "Premium Babol wood belan with superior quality and finish. Perfect for professional chefs.",
    features: [
      "Premium Babol wood",
      "Superior quality",
      "Professional grade",
      "Excellent finish",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 20,
    name: "Long Handle Belan",
    slug: "long-handle-belan",
    category: "Belan",
    price: 25,
    oldPrice: 33,
    discount: 24,
    stock: 350,
    rating: 4.6,
    reviews: 195,
    brand: "AG Traders",
    material: "Wood",
    color: "Natural",
    weight: "120g",
    length: "15 inch",
    image: "/src/assets/Images/lambi.png",
    description:
      "Extra long handle belan for comfortable grip and better control. Ideal for large dough preparations.",
    features: [
      "Long handle",
      "Comfortable grip",
      "Better control",
      "Large preparations",
    ],
    shippingTime: "3-5 days",
  },

  // Matani Products
  {
    id: 21,
    name: "Gool Gotani Matani",
    slug: "gool-gotani-matani",
    category: "Matani",
    price: 17,
    oldPrice: 23,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Babool Wood",
    color: "Yellow",
    weight: "100g",
    diameter: "4 inch",
    image: "/src/assets/Images/goolgotani.png",
    description:
      "Premium Gool Matani with natural wood finish. Perfect for grinding spices and making pastes.",
    features: ["Grinding quality", "Natural finish", "Babool wood", "Durable"],
    shippingTime: "3-5 days",
  },
  {
    id: 22,
    name: "Small Matani",
    slug: "small-matani",
    category: "Matani",
    price: 12,
    oldPrice: 16,
    discount: 25,
    stock: 700,
    rating: 4.5,
    reviews: 180,
    brand: "AG Traders",
    material: "Wood",
    color: "Natural",
    weight: "80g",
    diameter: "3.5 inch",
    image: "/src/assets/Images/small.png",
    description:
      "Compact and lightweight matani perfect for small grinding tasks. Easy to handle and store.",
    features: ["Compact size", "Lightweight", "Easy to handle", "Small tasks"],
    shippingTime: "3-5 days",
  },
];

const addProductsToFirestore = async () => {
  console.log("Starting upload...");
  for (const product of products) {
    try {
      // "products" collection mein data add ho raha hai
      await addDoc(collection(db, "products"), product);
      console.log(`✅ Added: ${product.name}`);
    } catch (error) {
      console.error(`❌ Error adding ${product.name}:`, error);
    }
  }
  console.log("Upload process finished.");
};

addProductsToFirestore();
