const blogPosts = [
  {
    id: 1,
    title: "Why Wooden Chakla & Belan Are Best for Your Kitchen",
    category: "Kitchen Tips",
    date: "15 Feb 2026",
    // Replace with your local path, e.g., "/images/wooden-set.jpg"
    image: "src/Images/WhatsApp Image 2026-02-15 at 4.46.06 AM (1).jpeg",
    excerpt:
      "Discover why traditional wooden chakla belan is healthier and long-lasting compared to plastic alternatives.",
    content:
      "Wooden chakla and belan have been used in Indian kitchens for generations. They are eco-friendly, durable, and provide better grip while rolling rotis. Unlike plastic, wood is a natural material that doesn't leach chemicals into your dough.",
  },
  {
    id: 2,
    title: "The Art of the Gothni: Traditional Wooden Churners",
    category: "Product Guide",
    date: "12 Feb 2026",
    // This refers to the 'gothni' image you uploaded
    image: "path_to_your_gothni_image.jpg",
    excerpt:
      "Explore the traditional 'Gothni' used for churning buttermilk and blending lentils perfectly.",
    content:
      "The Gothni (wooden masher/churner) is an essential tool in rural kitchens. Handcrafted from premium wood, it ensures the authentic taste of lassi and dals remains intact without the heat generated by electric blenders.",
  },
  {
    id: 3,
    title: "Handcrafted 14-inch Professional Belans",
    category: "Product News",
    date: "10 Feb 2026",
    // This refers to the '14 inc' rolling pins image
    image: "path_to_your_14_inch_belan_image.jpg",
    excerpt:
      "Our new collection of 14-inch handcrafted rolling pins is designed for professional precision.",
    content:
      "Each 14-inch belan is turned with precision to ensure a smooth finish and perfect weight distribution. Ideal for large rotis, parathas, and commercial kitchen use.",
  },
  {
    id: 4,
    title: "How to Maintain Your Wooden Kitchen Products",
    category: "Care Guide",
    date: "5 Feb 2026",
    image: "https://images.unsplash.com/photo-1590080877777-58e10f5c5e0f",
    excerpt:
      "Simple tips to increase the life of your wooden belan, chakla and spoons.",
    content:
      "Avoid soaking wooden products in water for long hours. Apply food-safe oil (like coconut or mineral oil) occasionally to prevent the wood from drying out and cracking.",
  },
];

export default blogPosts;
