import yellow from "../../assets/Images/yellow.png";
import whitebelan from "../../assets/Images/whitebelan.png";
import Polishbelan from "../../assets/Images/whiteLine.png";
import neemchakla from "../../assets/Images/neemCakla.png";
import spacialBelan from "../../assets/Images/Specialbelan.png";
import sarmika from "../../assets/Images/sarmika.png";
import belan14 from "../../assets/Images/14inchbelan.png";
import belan12 from "../../assets/Images/babol2.png";
import babolbelan from "../../assets/Images/goolbelan.png";
import akand from "../../assets/Images/akandCakala.png";
import goolgotani from "../../assets/Images/goolgotani.png";
import babolgool from "../../assets/Images/babolgool.png";

export const CATEGORIES = ["All", "Chakla", "Belan", "Matani"];

export const products = [
  {
    id: 1,
    name: "Premium Yellow Wooden Chakla",
    slug: "premium-yellow-wooden",
    category: "Chakla",
    price: 55,
    oldPrice: 75,
    discount: 27,
    stock: 45,
    rating: 4.8,
    reviews: 128,
    brand: "AG Traders",
    material: "Hardwood",
    color: "Yellow Polish",
    weight: "200g",
    diameter: "9 inch",
    image: yellow,
    description:
      "Premium quality yellow polished wooden chakla made from strong hardwood. Smooth finish, comfortable grip and perfect for daily roti, paratha and puri making. Handcrafted with precision for durability and performance.",
    features: [
      "Anti-slip surface",
      "Eco-friendly",
      "Lifetime durability",
      "Smooth finish",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 2,
    name: "White Natural Belan",
    slug: "white-belan",
    category: "Belan",
    price: 16,
    oldPrice: 20,
    discount: 20,
    stock: 30,
    rating: 4.6,
    reviews: 96,
    brand: "AG Traders",
    material: "Wood",
    color: "Natural White",
    weight: "100g",
    length: "12 inch",
    image: whitebelan,
    description:
      "Heavy and durable wooden belan with smooth surface. Anti-bacterial natural wood, perfect for daily kitchen use and professional rolling.",
    features: ["Lightweight", "Non-toxic", "Easy to clean", "Perfect balance"],
    shippingTime: "3-5 days",
  },
  {
    id: 3,
    name: "Premium White Wood Belan",
    slug: "white-wood-belan",
    category: "Belan",
    price: 18,
    oldPrice: 24,
    discount: 25,
    stock: 50,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Polished Wood",
    color: "Light White",
    weight: "500g",
    length: "9 inch",
    image: Polishbelan,
    description:
      "Premium wood belan with natural grains and strong body. Long-lasting and perfect balance for smooth rolling of all types of dough.",
    features: [
      "Natural grain patterns",
      "Smooth rolling",
      "Durable",
      "Professional grade",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 4,
    name: "Double Polish Neem Chakla",
    slug: "double-polish-chakla",
    category: "Chakla",
    price: 65,
    oldPrice: 90,
    discount: 28,
    stock: 50,
    rating: 4.9,
    reviews: 210,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Dark Brown",
    weight: "300g",
    diameter: "10 inch",
    image: neemchakla,
    description:
      "Premium neem wood chakla with natural anti-bacterial properties. Double polished for smooth surface and long-lasting durability.",
    features: [
      "Anti-bacterial",
      "Double polished",
      "Premium finish",
      "Eco-friendly",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 5,
    name: "Double Polish Belan",
    slug: "double-polish-belan",
    category: "Belan",
    price: 65,
    oldPrice: 90,
    discount: 28,
    stock: 50,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Neem Wood",
    color: "Light Brown",
    weight: "200g",
    length: "10 inch",
    image: spacialBelan,
    description:
      "Premium neem wood belan with double polishing process. Strong, durable, and perfect for professional kitchen use.",
    features: [
      "Neem wood benefits",
      "Double polished",
      "Durable",
      "Professional quality",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 6,
    name: "Sarmika Wooden Chakla",
    slug: "sarmika-cakla",
    category: "Chakla",
    price: 34,
    oldPrice: 47,
    discount: 28,
    stock: 500,
    rating: 4.7,
    reviews: 210,
    brand: "AG Traders",
    material: "Sarmika Wood",
    color: "Light Brown",
    weight: "200g",
    diameter: "9 inch",
    image: sarmika,
    description:
      "Premium Sarmika wood chakla with natural grains and strong body. Long-lasting and perfect balance for smooth rolling.",
    features: ["Smooth surface", "Lightweight", "Durable", "Natural wood"],
    shippingTime: "3-5 days",
  },
  {
    id: 7,
    name: "Polish Belan 14 Inch",
    slug: "polish-belan-14",
    category: "Belan",
    price: 22,
    oldPrice: 30,
    discount: 27,
    stock: 500,
    rating: 4.7,
    reviews: 212,
    brand: "AG Traders",
    material: "Polish Wood",
    color: "Light White",
    weight: "130g",
    length: "14 inch",
    image: belan14,
    description:
      "Premium wooden belan with natural grains and strong body. Long-lasting and perfect balance for smooth rolling of dough.",
    features: ["Extra long", "Lightweight", "Smooth rolling", "Easy grip"],
    shippingTime: "3-5 days",
  },
  {
    id: 8,
    name: "Babol Polish Belan 12 Inch",
    slug: "babol-belan-12",
    category: "Belan",
    price: 22,
    oldPrice: 30,
    discount: 27,
    stock: 500,
    rating: 4.7,
    reviews: 212,
    brand: "AG Traders",
    material: "Babol Wood",
    color: "Light White",
    weight: "130g",
    length: "12 inch",
    image: belan12,
    description:
      "Premium Babol wood belan with smooth polishing. Perfect balance and strength for daily kitchen use.",
    features: [
      "Babol wood quality",
      "Well-balanced",
      "Smooth finish",
      "Durable",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 9,
    name: "Babol Gool Belan",
    slug: "babol-gool-belan",
    category: "Belan",
    price: 24,
    oldPrice: 32,
    discount: 25,
    stock: 500,
    rating: 4.8,
    reviews: 215,
    brand: "AG Traders",
    material: "Babol Gool Wood",
    color: "Light White",
    weight: "130g",
    length: "12 inch",
    image: babolbelan,
    description:
      "Premium Babol Gool wood belan with exceptional smoothness. Professional grade quality for perfect roti rolling.",
    features: [
      "Premium quality",
      "Smooth surface",
      "Long-lasting",
      "Professional grade",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 10,
    name: "Akand Premium Chakla",
    slug: "akand-chakla",
    category: "Chakla",
    price: 95,
    oldPrice: 129,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Akand Wood",
    color: "Light White",
    weight: "250g",
    diameter: "10 inch",
    image: akand,
    description:
      "Premium Akand wood chakla with exceptional durability and smooth finish. Best choice for professional use.",
    features: [
      "Premium Akand wood",
      "Extra durable",
      "Smooth surface",
      "Professional use",
    ],
    shippingTime: "3-5 days",
  },
  {
    id: 11,
    name: "Gool Gotani Matani",
    slug: "gool-gotani",
    category: "Matani",
    price: 17,
    oldPrice: 23,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Babool Wood",
    color: "Yellow",
    weight: "100g",
    diameter: "4 inch",
    image: goolgotani,
    description:
      "Premium Gool Matani with natural wood finish. Perfect for grinding spices and making pastes.",
    features: ["Grinding quality", "Natural finish", "Babool wood", "Durable"],
    shippingTime: "3-5 days",
  },
  {
    id: 12,
    name: "Gool Belan Polish Premium",
    slug: "gool-belan",
    category: "Belan",
    price: 26,
    oldPrice: 35,
    discount: 26,
    stock: 500,
    rating: 4.9,
    reviews: 260,
    brand: "AG Traders",
    material: "Babool Gool Wood",
    color: "Brown",
    weight: "150g",
    length: "12 inch",
    image: babolgool,
    description:
      "Premium Gool Belan wood with natural grains and strong body. Excellent for professional kitchen use.",
    features: [
      "Premium wood",
      "Smooth rolling",
      "Durable construction",
      "Professional quality",
    ],
    shippingTime: "3-5 days",
  },
];

// Services Data
export const services = [
  {
    id: 1,
    title: "Premium Quality Assurance",
    description:
      "Every product undergoes strict quality checks to ensure durability and excellence",
    icon: "✓",
    color: "from-blue-500 to-blue-600",
    details: "We maintain highest quality standards in our wooden crafts",
  },
  {
    id: 2,
    title: "Fast & Reliable Shipping",
    description:
      "Quick delivery with proper packaging to ensure products reach in perfect condition",
    icon: "🚚",
    color: "from-green-500 to-green-600",
    details: "Free shipping on orders above ₹500 with 3-5 days delivery",
  },
  {
    id: 3,
    title: "100% Authentic Products",
    description:
      "All our wooden items are handcrafted using traditional methods and premium materials",
    icon: "🎯",
    color: "from-purple-500 to-purple-600",
    details: "Direct manufacturing with zero middlemen",
  },
  {
    id: 4,
    title: "Expert Customer Support",
    description:
      "24/7 customer support to assist you with any queries or concerns",
    icon: "💬",
    color: "from-orange-500 to-orange-600",
    details: "Dedicated support team ready to help anytime",
  },
  {
    id: 5,
    title: "Easy Returns & Refunds",
    description:
      "Hassle-free 30-day return policy for complete customer satisfaction",
    icon: "↩️",
    color: "from-red-500 to-red-600",
    details: "No questions asked return policy",
  },
  {
    id: 6,
    title: "Bulk Order Discounts",
    description:
      "Special discounts available for wholesale and bulk orders for businesses",
    icon: "🏭",
    color: "from-indigo-500 to-indigo-600",
    details: "Corporate bulk pricing available",
  },
];

// Testimonials Data
export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    role: "Homemaker",
    image: "👩",
    rating: 5,
    comment:
      "Best quality wooden items! My kitchen setup feels premium now. The chakla and belan are so smooth and durable.",
    location: "Mumbai, India",
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    role: "Chef",
    image: "👨",
    rating: 5,
    comment:
      "As a professional chef, I demand quality. AG Traders never disappoints. Their products are used in my restaurant.",
    location: "Delhi, India",
  },
  {
    id: 3,
    name: "Anjali Patel",
    role: "Business Owner",
    image: "👩",
    rating: 4.8,
    comment:
      "Excellent customer service and fast delivery. Bulk orders handled professionally. Highly recommended!",
    location: "Ahmedabad, India",
  },
  {
    id: 4,
    name: "Vikram Singh",
    role: "Restaurant Owner",
    image: "👨",
    rating: 5,
    comment:
      "Switched to AG Traders for all our wooden kitchen items. Quality is unmatched and prices are very competitive.",
    location: "Bangalore, India",
  },
  {
    id: 5,
    name: "Sneha Das",
    role: "Kitchen Enthusiast",
    image: "👩",
    rating: 4.9,
    comment:
      "Love the attention to detail in their products. Each item is crafted with precision and care.",
    location: "Kolkata, India",
  },
  {
    id: 6,
    name: "Arjun Verma",
    role: "Retailer",
    image: "👨",
    rating: 5,
    comment:
      "Perfect supplier for our retail shop. Products are premium and customers keep coming back.",
    location: "Pune, India",
  },
];
